### ISSUE TITLE
Bug NHMA crashes the Digi app when taxon ID is entered

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#474]
**Describe the bug**
When being logged in under NHMA and submitting a Taxonomic ID will crash the app.
  

**To Reproduce**
1. Log in under NHMA and choose NHMA Entomology
2. Submit an ID number (any integer < 1000) in the Taxon number box
3. Press Enter
4. Fatal crash
5. Log:
```[02-02 10:57:09] p20044 {data_access.py:142} DEBUG - SELECT * FROM taxonname WHERE idnumber =121  LIMIT 1
[02-02 10:57:11] p20044 {DaSSCo.py:19} ERROR - No item with that key
[02-02 10:57:11] p20044 {DaSSCo.py:21} ERROR - Traceback (most recent call last):
  File "DaSSCo.py", line 17, in main
  File "home_screen.py", line 74, in __init__
  File "home_screen.py", line 137, in main
  File "specimen_data_entry.py", line 86, in __init__
  File "specimen_data_entry.py", line 467, in main
  File "models\model.py", line 237, in setFields
IndexError: No item with that key
```

**Expected behavior**
A prompt stating that the ID number doesn't exist would be sufficient.

**Please complete the following information:**
 - version: Mass Digitization App version 1.1.24
 - nothing is added to the DB when crashing

**Additional context**
As an aside: The app allows full taxonomy access even though one is logged in under NHMA and entomology.

**Comment by FedorSteeman** [comment]
Fixed and solution committed and pushed.
