### ISSUE TITLE
Error message when trying to install DigiApp

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#505]
When @hansviborg tried to install the DigiApp on his local computer at NHMA, an error message came up. It turns out that the app is not running correctly from the OneDrive path and they had to copy the file to the C drive. The log file had the following info:
Traceback (most recent call last):
  File "DaSSCo.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "home_screen.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\collection.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\model.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "specify_interface.py", line 26, in <module>
  File "data_access.py", line 50, in __init__
  File "data_access.py", line 43, in __init__
sqlite3.OperationalError: unable to open database file

At the moment, it seems to be working, but this will need investigating as to why this happened.

**Comment by PipBrewer** [comment]
Issue not raised again. Closing ticket. Can re-examine if happens again.
